# DATABASE CONFIGURATION
jbh.schema.name.products=finance
quarkus.datasource.finance.db-kind=postgresql
quarkus.datasource.finance.username=${DATABASE_USERNAME:postgres}
quarkus.datasource.finance.password=${DATABASE_PASSWORD:postgres}
quarkus.datasource.finance.jdbc.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/jbh_finance}?currentSchema=${jbh.schema.name.products}
# ===============================================
# HIBERNATE ORM CONFIGURATION
# ===============================================
quarkus.hibernate-orm.finance.datasource=${jbh.schema.name.products}
quarkus.hibernate-orm.finance.packages=com.jbh.finance.infra.adapters.out.persistence
quarkus.hibernate-orm.finance.schema-management.create-schemas=true
%dev.quarkus.hibernate-orm.finance.database.generation=none
%prod.quarkus.hibernate-orm.finance.database.generation=none
# ===============================================
# LIQUIBASE CONFIGURATION
# ===============================================
quarkus.liquibase.finance.liquibase-schema-name=finance
quarkus.liquibase.finance.schemas=finance
# Finance Liquibase
quarkus.liquibase.finance.change-log=db/finance-db-master.xml
quarkus.liquibase.finance.datasource=finance
quarkus.liquibase.finance.migrate-at-start=true
# Gateway Client Configuration
jbh.gateway.base-url=${JBH_GATEWAY_URL:http://localhost:8080}

