<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>jbh-account-domain</artifactId>
  <build>
    <plugins>
      <!-- JACOCO -->
      <plugin>
        <artifactId>jacoco-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
            <id>prepare-agent</id>
          </execution>
          <execution>
            <goals>
              <goal>report</goal>
            </goals>
            <id>report</id>
            <phase>verify</phase>
          </execution>
        </executions>
        <groupId>org.jacoco</groupId>
      </plugin>

      <!-- PMD Analysis -->
      <plugin>
        <artifactId>maven-pmd-plugin</artifactId>
        <configuration>
          <failOnViolation>${pmd.failOnViolation}</failOnViolation>
          <printFailingErrors>true</printFailingErrors>
          <rulesets>
            <ruleset>../pmd-ruleset-account.xml</ruleset>
          </rulesets>
          <targetJdk>${java.version}</targetJdk>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
        <version>${maven-pmd-plugin.version}</version>
      </plugin>

    </plugins>
  </build>

  <dependencies>
    <!-- Add Lombok Dependency -->
    <dependency>
      <artifactId>lombok</artifactId>
      <groupId>org.projectlombok</groupId>
      <scope>provided</scope>
    </dependency>

    <!-- Logging Dependencies -->
    <dependency>
      <artifactId>slf4j-api</artifactId>
      <groupId>org.slf4j</groupId>
    </dependency>
  </dependencies>

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <artifactId>jbh-account</artifactId>
    <groupId>com.jbh</groupId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>

  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>


</project>