# DATABASE CONFIGURATION
jbh.schema.name.products=productmgmt
quarkus.datasource.productmgmt.db-kind=postgresql
quarkus.datasource.productmgmt.username=${DATABASE_USERNAME:postgres}
quarkus.datasource.productmgmt.password=${DATABASE_PASSWORD:postgres}
quarkus.datasource.productmgmt.jdbc.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/jbh_finance}?currentSchema=${jbh.schema.name.products}
# ===============================================
# HIBERNATE ORM CONFIGURATION
# ===============================================
quarkus.hibernate-orm.productmgmt.datasource=${jbh.schema.name.products}
quarkus.hibernate-orm.productmgmt.packages=com.jbh.products.infra.adapters.out.persistence
quarkus.hibernate-orm.productmgmt.schema-management.create-schemas=true
%dev.quarkus.hibernate-orm.productmgmt.database.generation=none
%prod.quarkus.hibernate-orm.productmgmt.database.generation=none
# ===============================================
# LIQUIBASE CONFIGURATION
# ===============================================
quarkus.liquibase.productmgmt.liquibase-schema-name=productmgmt
quarkus.liquibase.productmgmt.schemas=productmgmt
# Accounts Liquibase
quarkus.liquibase.productmgmt.change-log=db/productmgmt-db-master.xml
quarkus.liquibase.productmgmt.datasource=productmgmt
quarkus.liquibase.productmgmt.migrate-at-start=true
# Gateway Client Configuration
jbh.gateway.base-url=${JBH_GATEWAY_URL:http://localhost:8080}

