package com.jbh.account.domain.vo;

public enum AccountMovementMetadataKey {
  // INVESTMENT_WITHDRAWAL
  TARGET_INTERNAL_ACCOUNT_ID,
  TARGET_INTERNAL_ACCOUNT_NAME,
  TARGET_EXTERNAL_ACCOUNT_NAME,

  // INVESTMENT_INCOME
  INVESTMENT_INCOME_ACCOUNT,

  // FILE_IMPORT
  FILE_IMPORT_TAG,
  FILE_IMPORTED_AT_TAG,
}
