account.api.base-path=/jbh-accounts/api
# DATABASE CONFIGURATION
jbh.schema.name.accounts=acctmgmt
quarkus.datasource.acctmgmt.db-kind=postgresql
quarkus.datasource.acctmgmt.username=${DATABASE_USERNAME:postgres}
quarkus.datasource.acctmgmt.password=${DATABASE_PASSWORD:postgres}
quarkus.datasource.acctmgmt.jdbc.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/jbh_finance}?currentSchema=${jbh.schema.name.accounts}
# ===============================================
# HIBERNATE ORM CONFIGURATION
# ===============================================
quarkus.hibernate-orm.acctmgmt.datasource=${jbh.schema.name.accounts}
quarkus.hibernate-orm.acctmgmt.packages=com.jbh.account.infra.adapters.out.persistence
%dev.quarkus.hibernate-orm.acctmgmt.database.generation=none
%prod.quarkus.hibernate-orm.acctmgmt.database.generation=none
# ===============================================
# LIQUIBASE CONFIGURATION
# ===============================================
quarkus.liquibase.acctmgmt.liquibase-schema-name=acctmgmt
quarkus.liquibase.acctmgmt.schemas=acctmgmt
# Accounts Liquibase
quarkus.liquibase.acctmgmt.change-log=db/changeLog-master.xml
quarkus.liquibase.acctmgmt.datasource=acctmgmt
quarkus.liquibase.acctmgmt.migrate-at-start=true
jbh.gateway.base-url=http://localhost:8080

