# HTTP Configuration
quarkus.http.port=7777

# CDI Configuration
quarkus.arc.remove-unused-beans=false
quarkus.arc.unremovable-types=com.company.jbh.**,**.jbh.**

# OpenAPI Configuration
quarkus.smallrye-openapi.info-title=JBH Modular Application API
quarkus.smallrye-openapi.info-version=${project.version}
quarkus.smallrye-openapi.scan-classes=true
quarkus.smallrye-openapi.auto-add-servers=true

# Package scanning
#quarkus.index-dependency.jbh-account-apis.artifact-id=jbh-account-apis

# Debug logging
quarkus.log.category."com.company.jbh".level=DEBUG
quarkus.log.category."io.quarkus.arc".level=DEBUG