# DATABASE CONFIGURATION
jbh.schema.name.userprefs=userprefs
quarkus.datasource.userprefs.db-kind=postgresql
quarkus.datasource.userprefs.username=${DATABASE_USERNAME:postgres}
quarkus.datasource.userprefs.password=${DATABASE_PASSWORD:postgres}
quarkus.datasource.userprefs.jdbc.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/jbh_finance}?currentSchema=${jbh.schema.name.userprefs}
# ===============================================
# HIBERNATE ORM CONFIGURATION
# ===============================================
quarkus.hibernate-orm.userprefs.datasource=${jbh.schema.name.userprefs}
quarkus.hibernate-orm.userprefs.packages=com.jbh.preferences.infra.adapters.out.persistence
%dev.quarkus.hibernate-orm.userprefs.database.generation=none
%prod.quarkus.hibernate-orm.userprefs.database.generation=none
# ===============================================
# LIQUIBASE CONFIGURATION
# ===============================================
quarkus.liquibase.userprefs.liquibase-schema-name=userprefs
quarkus.liquibase.userprefs.schemas=userprefs
quarkus.liquibase.userprefs.change-log=db/changeLog-master.xml
quarkus.liquibase.userprefs.datasource=userprefs
quarkus.liquibase.userprefs.migrate-at-start=true
# Gateway Client Configuration
jbh.gateway.base-url=${JBH_GATEWAY_URL:http://localhost:8080}
