# PREFERENCES DATABASE CONFIGURATION
jbh.schema.name.preferences=preferences
quarkus.datasource.preferences.db-kind=postgresql
quarkus.datasource.preferences.username=${DATABASE_USERNAME:postgres}
quarkus.datasource.preferences.password=${DATABASE_PASSWORD:postgres}
quarkus.datasource.preferences.jdbc.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/jbh_finance}?currentSchema=${jbh.schema.name.preferences}

# HIBERNATE ORM CONFIGURATION
quarkus.hibernate-orm.preferences.datasource=${jbh.schema.name.preferences}
quarkus.hibernate-orm.preferences.packages=com.jbh.preferences.infra.adapters.out.persistence
%dev.quarkus.hibernate-orm.preferences.database.generation=none
%prod.quarkus.hibernate-orm.preferences.database.generation=none

# LIQUIBASE CONFIGURATION
quarkus.liquibase.preferences.liquibase-schema-name=preferences
quarkus.liquibase.preferences.schemas=preferences
quarkus.liquibase.preferences.change-log=db/preferences-db-master.xml
quarkus.liquibase.preferences.datasource=preferences
quarkus.liquibase.preferences.migrate-at-start=true

# Gateway Client Configuration
jbh.gateway.base-url=${JBH_GATEWAY_URL:http://localhost:8080}
