notification.api.base-path=/jbh-notifications/api
# DATABASE CONFIGURATION
jbh.schema.name.notifications=notifications
quarkus.liquibase.change-log=db/notificationdb-master.xml
quarkus.liquibase.database-change-log-lock-table-name=DATABASECHANGELOGLOCK_notifications
quarkus.liquibase.database-change-log-table-name=DATABASECHANGELOG_notifications
quarkus.liquibase.migrate-at-start=true

quarkus.datasource.notifications.db-kind=postgresql
quarkus.datasource.notifications.username=${DATABASE_USERNAME:postgres}
quarkus.datasource.notifications.password=${DATABASE_PASSWORD:postgres}
quarkus.datasource.notifications.jdbc.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/jbh_finance}?currentSchema=notifications
# ===============================================
# HIBERNATE ORM CONFIGURATION
# ===============================================
quarkus.hibernate-orm.notifications.datasource=notifications
quarkus.hibernate-orm.notifications.packages=com.jbh.notification.infra.persistence
%dev.quarkus.hibernate-orm.notifications.database.generation=none
%prod.quarkus.hibernate-orm.notifications.database.generation=none
# ===============================================
# LIQUIBASE CONFIGURATION
# ===============================================
quarkus.liquibase.notifications.liquibase-schema-name=notifications
quarkus.liquibase.notifications.schemas=notifications
# Notifications Liquibase
quarkus.liquibase.notifications.change-log=db/notificationdb-master.xml
quarkus.liquibase.notifications.datasource=notifications
%dev.quarkus.liquibase.notifications.migrate-at-start=true
%prod.quarkus.liquibase.notifications.migrate-at-start=true